services:
    backend:
        build: ./backend
        ports: 
            - "8000:8000"
        networks:
            - my_net
        env_file:
            - ./backend/.env
        container_name: backend_container
        depends_on: 
            - mongodb

    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        container_name: Mongodb_container
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin4
            MONGO_INITDB_ROOT_PASSWORD: supersecretpassword
        volumes:
            - my_vol:/data/db
        networks:
            - my_net

volumes:
    my_vol:
  
networks:
    my_net: